/// Represents an individual crop recommendation plan generated by AI.
class CropPlanModel {
  final String id;
  final String cropName;
  final String cropIcon;
  final String tagline;
  final String durationDays;
  final String estimatedInvestmentPerAcre;
  final String estimatedProfitPerAcre;
  final String roiMultiplier;
  final Map<String, String> investmentBreakdown;
  final List<String> recommendedFertilizers; // Exactly 3 fertilizer names
  final String decisionRationale; // Concise explanation based on soil + weather data
  final List<FertilizerStep> fertilizerSchedule;
  final List<String> cultivationSteps;
  final String soilSuitabilityReason;
  final String climateSuitabilityReason;
  final DateTime createdAt;

  CropPlanModel({
    required this.id,
    required this.cropName,
    required this.cropIcon,
    required this.tagline,
    required this.durationDays,
    required this.estimatedInvestmentPerAcre,
    required this.estimatedProfitPerAcre,
    required this.roiMultiplier,
    required this.investmentBreakdown,
    required this.recommendedFertilizers,
    required this.decisionRationale,
    required this.fertilizerSchedule,
    required this.cultivationSteps,
    required this.soilSuitabilityReason,
    required this.climateSuitabilityReason,
    DateTime? createdAt,
  }) : createdAt = createdAt ?? DateTime.now();

  Map<String, dynamic> toJson() => {
        'id': id,
        'cropName': cropName,
        'cropIcon': cropIcon,
        'tagline': tagline,
        'durationDays': durationDays,
        'estimatedInvestmentPerAcre': estimatedInvestmentPerAcre,
        'estimatedProfitPerAcre': estimatedProfitPerAcre,
        'roiMultiplier': roiMultiplier,
        'investmentBreakdown': investmentBreakdown,
        'recommendedFertilizers': recommendedFertilizers,
        'decisionRationale': decisionRationale,
        'fertilizerSchedule': fertilizerSchedule.map((s) => s.toJson()).toList(),
        'cultivationSteps': cultivationSteps,
        'soilSuitabilityReason': soilSuitabilityReason,
        'climateSuitabilityReason': climateSuitabilityReason,
        'createdAt': createdAt.toIso8601String(),
      };

  factory CropPlanModel.fromJson(Map<String, dynamic> json) {
    // Extract 3 fertilizers
    List<String> ferts = (json['recommendedFertilizers'] as List<dynamic>?)
            ?.map((e) => e.toString())
            .toList() ??
        [];

    if (ferts.isEmpty) {
      // Fallback from fertilizerSchedule if present
      final sched = (json['fertilizerSchedule'] as List<dynamic>?);
      if (sched != null) {
        for (final item in sched) {
          if (item is Map<String, dynamic>) {
            final dose = item['recommendedDose']?.toString() ?? '';
            if (dose.isNotEmpty && !ferts.contains(dose)) ferts.add(dose);
          } else if (item != null) {
            ferts.add(item.toString());
          }
        }
      }
    }

    if (ferts.isEmpty) {
      ferts = [
        'Urea (Nitrogen Source)',
        'DAP (Di-ammonium Phosphate)',
        'MOP (Muriate of Potash)',
      ];
    }
    if (ferts.length > 3) ferts = ferts.sublist(0, 3);

    String name = json['cropName']?.toString() ?? 'Recommended Crop';
    name = name.trim();
    if (name.endsWith('/')) name = name.substring(0, name.length - 1).trim();
    if (name.contains('(') && !name.contains(')')) name = '$name)';

    return CropPlanModel(
      id: json['id']?.toString() ?? DateTime.now().millisecondsSinceEpoch.toString(),
      cropName: name,

      cropIcon: json['cropIcon']?.toString() ?? '🌾',
      tagline: json['tagline']?.toString() ?? 'High Yield & Optimum Return',
      durationDays: json['durationDays']?.toString() ?? '110 - 120 Days',
      estimatedInvestmentPerAcre:
          json['estimatedInvestmentPerAcre']?.toString() ?? '₹25,000',
      estimatedProfitPerAcre:
          json['estimatedProfitPerAcre']?.toString() ?? '₹75,000',
      roiMultiplier: json['roiMultiplier']?.toString() ?? '3.0x',
      investmentBreakdown: (json['investmentBreakdown'] as Map<String, dynamic>?)
              ?.map((k, v) => MapEntry(k, v.toString())) ??
          {
            'Seeds & Saplings': '₹4,500',
            'Fertilizers & Soil Amendments': '₹6,000',
            'Labour & Field Ops': '₹7,500',
            'Irrigation & Energy': '₹4,000',
            'Pesticides & Crop Protection': '₹3,000',
          },
      recommendedFertilizers: ferts,
      decisionRationale: json['decisionRationale']?.toString() ??
          'Decision based on soil N-P-K nutrient balance, temperature profile, and seasonal monsoon patterns.',
      fertilizerSchedule: (json['fertilizerSchedule'] as List<dynamic>?)
              ?.map((item) {
                if (item is Map<String, dynamic>) {
                  return FertilizerStep.fromJson(item);
                } else {
                  return FertilizerStep(
                    stage: 'Application',
                    timing: 'Seasonal',
                    recommendedDose: item.toString(),
                  );
                }
              })
              .toList() ??
          [],
      cultivationSteps: (json['cultivationSteps'] as List<dynamic>?)
              ?.map((item) => item.toString())
              .toList() ??
          [],
      soilSuitabilityReason:
          json['soilSuitabilityReason']?.toString() ?? 'Ideal soil nutrient match.',
      climateSuitabilityReason: json['climateSuitabilityReason']?.toString() ??
          'Optimal temperature and seasonal window.',
      createdAt: DateTime.tryParse(json['createdAt']?.toString() ?? '') ??
          DateTime.now(),
    );
  }
}

class FertilizerStep {
  final String stage;
  final String timing;
  final String recommendedDose;

  const FertilizerStep({
    required this.stage,
    required this.timing,
    required this.recommendedDose,
  });

  Map<String, dynamic> toJson() => {
        'stage': stage,
        'timing': timing,
        'recommendedDose': recommendedDose,
      };

  factory FertilizerStep.fromJson(Map<String, dynamic> json) {
    return FertilizerStep(
      stage: json['stage']?.toString() ?? 'Basal Application',
      timing: json['timing']?.toString() ?? 'During Sowing',
      recommendedDose:
          json['recommendedDose']?.toString() ?? 'DAP: 50 kg/acre, MOP: 25 kg/acre',
    );
  }
}

/// Represents a result batch containing 3 top recommended crop plans.
class CropRecommendationResult {
  final String id;
  final DateTime generatedAt;
  final String state;
  final String city;
  final String soilType;
  final String startMonth;
  final String? soilReportName;
  final String? liveWeatherSummary; // Real weather context
  final List<CropPlanModel> cropPlans;

  CropRecommendationResult({
    required this.id,
    required this.generatedAt,
    required this.state,
    required this.city,
    required this.soilType,
    required this.startMonth,
    this.soilReportName,
    this.liveWeatherSummary,
    required this.cropPlans,
  });

  Map<String, dynamic> toJson() => {
        'id': id,
        'generatedAt': generatedAt.toIso8601String(),
        'state': state,
        'city': city,
        'soilType': soilType,
        'startMonth': startMonth,
        'soilReportName': soilReportName,
        'liveWeatherSummary': liveWeatherSummary,
        'cropPlans': cropPlans.map((c) => c.toJson()).toList(),
      };

  factory CropRecommendationResult.fromJson(Map<String, dynamic> json) {
    return CropRecommendationResult(
      id: json['id']?.toString() ?? DateTime.now().millisecondsSinceEpoch.toString(),
      generatedAt: DateTime.tryParse(json['generatedAt']?.toString() ?? '') ??
          DateTime.now(),
      state: json['state']?.toString() ?? '',
      city: json['city']?.toString() ?? '',
      soilType: json['soilType']?.toString() ?? '',
      startMonth: json['startMonth']?.toString() ?? '',
      soilReportName: json['soilReportName']?.toString(),
      liveWeatherSummary: json['liveWeatherSummary']?.toString(),
      cropPlans: (json['cropPlans'] as List<dynamic>?)
              ?.map((item) => CropPlanModel.fromJson(item as Map<String, dynamic>))
              .toList() ??
          [],
    );
  }
}

/// Model for an adopted farm saved under "My Farms"
class SavedFarmModel {
  final String id;
  final String farmName;
  final DateTime adoptedAt;
  final String location;
  final CropPlanModel cropPlan;

  SavedFarmModel({
    required this.id,
    required this.farmName,
    required this.adoptedAt,
    required this.location,
    required this.cropPlan,
  });

  Map<String, dynamic> toJson() => {
        'id': id,
        'farmName': farmName,
        'adoptedAt': adoptedAt.toIso8601String(),
        'location': location,
        'cropPlan': cropPlan.toJson(),
      };

  factory SavedFarmModel.fromJson(Map<String, dynamic> json) {
    return SavedFarmModel(
      id: json['id']?.toString() ?? DateTime.now().millisecondsSinceEpoch.toString(),
      farmName: json['farmName']?.toString() ?? 'My Field',
      adoptedAt: DateTime.tryParse(json['adoptedAt']?.toString() ?? '') ??
          DateTime.now(),
      location: json['location']?.toString() ?? 'Location',
      cropPlan: CropPlanModel.fromJson(json['cropPlan'] as Map<String, dynamic>),
    );
  }
}
